### ISSUE TITLE
supporting MLR strategy with more than one variable

### ISSUE THREAD

**Issue by alinaciuysal** [alinaciuysal/OEDA#20]
1) knob object creation should be updated accordingly for MlrStrategy.py (similar to self-optimizer strategy)

2) makeParamSet() of ParamHelpers package should be called within a for loop to create desired parameter set.
[See example](https://www.rdocumentation.org/packages/smoof/versions/1.5.1/topics/makeSingleObjectiveFunction)

**Comment by alinaciuysal** [comment]
[implemented here](https://github.com/alinaciuysal/OEDA/commit/dbd3f973eec30c29083680eda48cd6501f0d0061)

**Comment by iliasger** [comment]
Excellent
